services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: lab10-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
