spring:
  application:
    name: StockService
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        instance-id: ${spring.application.name}-${server.port}
        health-check-url: http://host.docker.internal:8900/actuator/health
        health-check-interval: 10s
server:
  port: 8900

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

