server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:file://${user.dir}/../config-repo}
          default-label: ${CONFIG_REPO_LABEL:main}
          clone-on-start: true
          force-pull: true
          username: ${CONFIG_REPO_USERNAME:}
          password: ${CONFIG_REPO_PASSWORD:}
